---
title: Remove 'Extract' from Context Menu
description: Removes 'Extract' from Context Menu
actions:
  - !cmd:
    command: 'reg import "AtlasDesktop\4. Interface Tweaks\Context Menus\Extract\Remove Extract (default).reg"'
    exeDir: true
    wait: true
