readme:
- '**/README.md'

actions:
- .github/workflows/**/*
- .github/labeler.yml

# Playbook

playbook:
- src/**/*

appx:
- src/Configuration/atlas/appx.yml

components:
- src/Configuration/atlas/components.yml
- src/Configuration/atlas/packages.yml

config:
- src/Configuration/atlas/config.yml

services:
- src/Configuration/atlas/services.yml

tweaks:
- src/Configuration/tweaks.yml
- src/Configuration/tweaks/**/*

desktop folder:
- src/Executables/AtlasDesktop/**/*
