---
title: Disable Experimentation
description: Disallows Microsoft from using your computer as a test for certain features for privacy and stability
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\System\AllowExperimentation'
    value: 'Value'
    data: '0'
    type: REG_DWORD
