---
title: Configure OEM Information
description: Configures OEM information to contain the Atlas version and the Atlas Discord server
actions:
  - !powerShell:
    command: |
      $version = 'AtlasVersionUndefined'

      Write-Output 'Setting boot entry name...'
      bcdedit /set description """AtlasOS $(('10', '11')[[int]([System.Environment]::OSVersion.Version.Build -ge 22000)]) $version"""

      Write-Output 'Setting other versioned OEM information...'
      $reportedVer = """Atlas Playbook $version"""
      # Shows in Settings
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation' -Name 'Model' -Value $reportedVer -Force
      # Shows in winver
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name 'RegisteredOrganization' -Value $reportedVer -Force
    wait: true
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Manufacturer'
    data: 'Atlas Team'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportURL'
    data: 'https://discord.atlasos.net'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportPhone'
    data: 'https://github.com/Atlas-OS/Atlas'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Atlas'
    value: 'WinreFallbackFixed'
    data: '1'
    type: REG_SZ
