---
title: Enable Notifications
description: Notifications were turned off at the start of the Playbook to prevent random notifications from interfering with the process. This task re-enables notifications.
actions:
  - !cmd:
    command: 'ENABLENOTIFS.cmd'
    exeDir: true
    wait: true
    runas: currentUserElevated
