---
title: Disable NVIDIA Control Panel Telemetry
description: Disables NVIDIA Control Panel telemetry for privacy
actions:
  - !registryValue:
    path: 'HKCU\Software\NVIDIA Corporation\NVControlPanel2\Client'
    value: 'OptInOrOutPreference'
    data: '0'
    type: REG_DWORD
